RANDOMWALK-64 Add dto and controllers
ru-random-walk/matcher-service pull request #3
Opened 2024-11-10 18:09 UTC by kryakobess

2024-11-11 12:33 UTC, maksmolchdmitr requested changes

2024-11-11 12:33 UTC, maksmolchdmitr commented on src/main/java/ru/randomwalk/matcherservice/model/dto/LocationDto.java
> +        @NotNull
Аннотации @Nullable нужны для своевременного предотвращения NPE, @NotNull скажет IDE только что поле не будет null, но про остальных она ничего не скажет!
Поэтому 2 варианта:
- либо использовать @Nullable для других полей, а @NotNull можно убрать
- либо использовать package-info для всех папок вроде (такой вариант кстати в Яшке был)
https://stackoverflow.com/questions/13310994/set-findbugs-notnull-as-default-for-all-classes-under-a-package

2024-11-11 12:33 UTC, maksmolchdmitr commented on src/main/java/ru/randomwalk/matcherservice/model/dto/request/AppointmentRequestDto.java
> +        @NotNull
ю

2024-11-11 12:33 UTC, maksmolchdmitr commented on src/main/java/ru/randomwalk/matcherservice/model/dto/request/AvailableTimeRequestDto.java
> +        @NotNull
ю

2024-11-11 12:33 UTC, maksmolchdmitr commented on src/main/java/ru/randomwalk/matcherservice/model/dto/request/AvailableTimeRequestDto.java
пока сырая дтошка - наверно потому что нигде не используется

2024-11-11 12:33 UTC, maksmolchdmitr commented on src/main/java/ru/randomwalk/matcherservice/controller/AppointmentController.java
Put это замена целиком, а Patch это изменение отдельных полей
https://ru.stackoverflow.com/questions/1070324/%D0%A0%D0%B0%D0%B7%D0%BD%D0%B8%D1%86%D0%B0-%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B8%D1%8F-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-put-%D0%B8-patch-%D0%B2-rest
Не лучше бы добавить PatchMapping(..) ручки для именно добавления? (Открытый вопрос)

2024-11-11 17:16 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/model/dto/request/AvailableTimeRequestDto.java
> +        Integer walkCount,
Мы же вроде говорили, что walk count может ставится пользователем, но не больше допустимого лимита

2024-11-11 17:16 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/model/dto/LocationDto.java
> +        @NotNull
Это валидационный notNull

2024-11-16 17:44 UTC, maksmolchdmitr approved these changes

2024-11-16 18:14 UTC, merged