RANDOMWALK-66 Implement matching algorithm
ru-random-walk/matcher-service pull request #4
Opened 2024-12-06 11:14 UTC by kryakobess

2024-12-07 11:49 UTC, kryakobess reviewed
😶‍🌫️

2024-12-12 14:17 UTC, maksmolchdmitr requested changes

2024-12-12 14:24 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/config/MatcherProperties.java
> +public class MatcherProperties {
вроде бы я уже нарывался на какие-то проблемы с тем, что менял подобные классы на рекорды на ауфе. Из-за этого решил сделать просто классом

2024-12-12 14:25 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/MatcherServiceApplication.java
> +@EnableAsync
я исправил это в следующих мр, все инжектится

2024-12-12 14:26 UTC, maksmolchdmitr commented on src/main/java/ru/randomwalk/matcherservice/config/MatcherProperties.java
> +public class MatcherProperties {
Здесь вроде не вижу проблемы использовать рекорд, чтобы не писать 100500 аннотаций)

2024-12-12 14:29 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/config/MatcherProperties.java
> +public class MatcherProperties {
я не против аннотаций

2024-12-12 14:30 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/config/MatcherProperties.java
> +public class MatcherProperties {
Не вижу проблемы использовать аннотации, чтобы не переписывать все геттеры)

2024-12-13 12:43 UTC, maksmolchdmitr requested changes

2024-12-14 07:16 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/model/entity/AvailableTime.java
> +    }
Геттеры не часть какого-либо интерфейса или абстрактного класса

2024-12-14 11:54 UTC, kryakobess commented on src/main/java/ru/randomwalk/matcherservice/model/model/AvailableTimeOverlapModel.java
> +        AvailableTime secondOverlappingAvailableTime
это просто нейминг, это элемент массивов first и second из входных данных, которые пересекаются

2024-12-14 15:31 UTC, maksmolchdmitr approved these changes

2024-12-15 12:30 UTC, merged